// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Bot struct {
	ID             int32              `json:"id"`
	UserID         int32              `json:"user_id"`
	Name           string             `json:"name"`
	Strategy       string             `json:"strategy"`
	Status         pgtype.Text        `json:"status"`
	WinRate        pgtype.Numeric     `json:"win_rate"`
	ProfitFactor   pgtype.Numeric     `json:"profit_factor"`
	Trades         pgtype.Int4        `json:"trades"`
	InitialHolding pgtype.Numeric     `json:"initial_holding"`
	Holding        pgtype.Numeric     `json:"holding"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           int32              `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	PasswordHash string             `json:"password_hash"`
}
